export const PRODUCTOS_RESPALDO = [
  {
    id: 'fallback-1',
    nombre: 'Pan de molde sin gluten',
    precio: 1850,
    categoria: 'Panificados',
    descripcion: 'Pan de molde esponjoso, ideal para sandwiches. Sin TACC.',
    imagen_url: '',
    stock: 12,
    activo: true,
    created_at: '2026-04-01T12:00:00.000Z',
  },
  {
    id: 'fallback-2',
    nombre: 'Pan de hamburguesa sin gluten',
    precio: 950,
    categoria: 'Panificados',
    descripcion: 'Pack de 4 panes de hamburguesa suaves y sin gluten.',
    imagen_url: '',
    stock: 10,
    activo: true,
    created_at: '2026-04-01T12:10:00.000Z',
  },
  {
    id: 'fallback-3',
    nombre: 'Facturas sin gluten',
    precio: 2200,
    categoria: 'Panificados',
    descripcion: 'Surtido de medialunas y vigilantes recien horneados.',
    imagen_url: '',
    stock: 8,
    activo: true,
    created_at: '2026-04-01T12:20:00.000Z',
  },
  {
    id: 'fallback-4',
    nombre: 'Fideos tallarines sin gluten',
    precio: 1100,
    categoria: 'Pastas',
    descripcion: 'Fideos de arroz y maiz con buena textura. Aptos celiaquia.',
    imagen_url: '',
    stock: 20,
    activo: true,
    created_at: '2026-04-01T12:30:00.000Z',
  },
  {
    id: 'fallback-5',
    nombre: 'Fideos tirabuzon sin gluten',
    precio: 1100,
    categoria: 'Pastas',
    descripcion: 'Tirabuzones de arroz ideales para salsas intensas.',
    imagen_url: '',
    stock: 20,
    activo: true,
    created_at: '2026-04-01T12:40:00.000Z',
  },
  {
    id: 'fallback-6',
    nombre: 'Noquis sin gluten',
    precio: 1400,
    categoria: 'Pastas',
    descripcion: 'Noquis de papa listos para cocinar. Sin TACC.',
    imagen_url: '',
    stock: 14,
    activo: true,
    created_at: '2026-04-01T12:50:00.000Z',
  },
  {
    id: 'fallback-7',
    nombre: 'Galletitas de arroz',
    precio: 750,
    categoria: 'Galletitas',
    descripcion: 'Galletitas crocantes de arroz para snack o desayuno.',
    imagen_url: '',
    stock: 18,
    activo: true,
    created_at: '2026-04-02T09:00:00.000Z',
  },
  {
    id: 'fallback-8',
    nombre: 'Galletitas de chocolate sin gluten',
    precio: 980,
    categoria: 'Galletitas',
    descripcion: 'Galletitas dulces con chips de chocolate. Sin TACC.',
    imagen_url: '',
    stock: 16,
    activo: true,
    created_at: '2026-04-02T09:10:00.000Z',
  },
  {
    id: 'fallback-9',
    nombre: 'Alfajores sin gluten',
    precio: 1650,
    categoria: 'Galletitas',
    descripcion: 'Alfajores rellenos de dulce de leche con coco.',
    imagen_url: '',
    stock: 12,
    activo: true,
    created_at: '2026-04-02T09:20:00.000Z',
  },
  {
    id: 'fallback-10',
    nombre: 'Premezcla para torta',
    precio: 1300,
    categoria: 'Postres y Dulces',
    descripcion: 'Premezcla lista para una torta humeda de vainilla.',
    imagen_url: '',
    stock: 15,
    activo: true,
    created_at: '2026-04-02T09:30:00.000Z',
  },
  {
    id: 'fallback-11',
    nombre: 'Brownie sin gluten',
    precio: 1500,
    categoria: 'Postres y Dulces',
    descripcion: 'Premezcla para brownie de chocolate intenso.',
    imagen_url: '',
    stock: 15,
    activo: true,
    created_at: '2026-04-02T09:40:00.000Z',
  },
  {
    id: 'fallback-12',
    nombre: 'Bizcochos de grasa sin gluten',
    precio: 1200,
    categoria: 'Panificados',
    descripcion: 'Bizcochos crujientes y sabrosos para mate o desayuno.',
    imagen_url: '',
    stock: 10,
    activo: true,
    created_at: '2026-04-02T09:50:00.000Z',
  },
  {
    id: 'fallback-13',
    nombre: 'Harina de arroz',
    precio: 850,
    categoria: 'Harinas',
    descripcion: 'Harina fina ideal para rebozados y reposteria.',
    imagen_url: '',
    stock: 22,
    activo: true,
    created_at: '2026-04-03T08:00:00.000Z',
  },
  {
    id: 'fallback-14',
    nombre: 'Premezcla para pan',
    precio: 1100,
    categoria: 'Harinas',
    descripcion: 'Premezcla especial para pan casero sin gluten.',
    imagen_url: '',
    stock: 18,
    activo: true,
    created_at: '2026-04-03T08:10:00.000Z',
  },
  {
    id: 'fallback-15',
    nombre: 'Harina de mandioca',
    precio: 720,
    categoria: 'Harinas',
    descripcion: 'Harina de mandioca versatil para cocina sin gluten.',
    imagen_url: '',
    stock: 20,
    activo: true,
    created_at: '2026-04-03T08:20:00.000Z',
  },
  {
    id: 'fallback-16',
    nombre: 'Tostadas de maiz',
    precio: 880,
    categoria: 'Galletitas',
    descripcion: 'Tostadas crocantes de maiz, ideales para desayuno.',
    imagen_url: '',
    stock: 17,
    activo: true,
    created_at: '2026-04-03T08:30:00.000Z',
  },
];